repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-json
  - id: check-symlinks
  - id: check-toml
  - id: check-xml
  - id: check-yaml
  - id: destroyed-symlinks
  - id: end-of-file-fixer
  - id: fix-byte-order-marker
  - id: mixed-line-ending
    args: [--fix=lf]
  - id: trailing-whitespace
- repo: local
  hooks:
  - id: cargo-fmt
    name: cargo fmt
    entry: cargo fmt
    args: [--all, --, --check]
    language: system
    types: [rust]
    pass_filenames: false
  - id: cargo-check
    name: cargo check
    entry: cargo check
    args: [--all-targets, --all-features, --config, "build.rustflags = ['-D', 'warnings']"]
    language: system
    types: [rust]
    pass_filenames: false
  - id: clippy
    name: clippy
    entry: cargo clippy
    args: [--all-targets, --all-features, --config, "build.rustflags = ['-D', 'warnings']"]
    language: system
    types: [rust]
    pass_filenames: false
  - id: cargo-doc
    name: cargo doc
    entry: cargo doc
    args: [--all-features, --config, "build.rustdocflags = ['-D', 'warnings']"]
    language: system
    types: [rust]
    pass_filenames: false
  - id: cargo-test
    name: cargo test
    entry: cargo test
    args: [--all-features, --config, "build.rustflags = ['-D', 'warnings']"]
    language: system
    types: [rust]
    pass_filenames: false
